# Generated by Django 4.2.17 on 2025-01-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
