# Generated by Django 4.2.17 on 2025-01-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_room_capacity_room_is_private_room_room_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=10, help_text='Maximum number of people')),
                ('is_private', models.BooleanField(default=False)),
                ('room_type', models.CharField(choices=[('SMALL', 'Small Meeting Room'), ('LARGE', 'Large Meeting Room'), ('CONF', 'Conference Room')], default='SMALL', max_length=10)),
            ],
        ),
    ]
