# Generated by Django 4.2.17 on 2025-01-15 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duration',
        ),
        migrations.AddField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 14, 15, 27, 998910)),
        ),
        migrations.AddField(
            model_name='check',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='check',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
