# Generated by Django 4.2.17 on 2025-01-15 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 14, 36, 23, 206319)),
        ),
    ]
