# Generated by Django 4.2.17 on 2025-01-15 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_alter_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetings.room'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 14, 54, 53, 223003)),
        ),
    ]
