# Generated by Django 4.2.17 on 2025-01-15 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_check_room_alter_check_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='room',
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 15, 25, 49, 512242)),
        ),
    ]
